#! /bin/sh
### BEGIN INIT INFO
# Provides:          gb
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run the Gigablast Search Engine
### END INIT INFO

case "$1" in
    start)
    	start-stop-daemon --start --background --exec /usr/bin/gb -- -d
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
